name: Execução diária do robô
on:
  schedule:
    - cron: '0 10 * * *'  # Executa diariamente às 10:00 UTC
  workflow_dispatch:
jobs:
  executar:
    runs-on: ubuntu-latest
    steps:
      - name: clonar repositório
        uses: actions/checkout@v3
      - name: Commit do relatório
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          if [ "$(git status --porcelain)" ]; then
            git add dados/relatorio.csv
            git commit -m "Atualização diária"
            git push
          else
            echo "Nenhuma alteração detectada. Nenhum commit necessário."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
